# Dockerfile.monolith
FROM go-rpc-base

WORKDIR /app

COPY . .

# Declare a VOLUME for persistent data
VOLUME /app/src/data

# Build server and client executables
RUN go mod tidy
RUN go build -o server ./rpc_server.go
RUN go build -o client ./rpc_client.go
RUN go build -o client_concurrent ./rpc_client_concurrent.go

# Set ENTRYPOINT to run the server by default when the container starts
ENTRYPOINT ["./server"]